apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
spec:
  containers:
  - image: aksregistrygitlab.azurecr.io/madhavigroup/k8s-data/sample:v1
    name: webapp
    imagePullPolicy: Always
  restartPolicy: Always
  imagePullSecrets:
    - name: acr-auth